function() {    
    
    karate.log('Env Params :', karate.env);
     
     var envName = karate.env;
  
  // var appName = karate.properties['telus.appName'];
     // karate.log('telus.appName system property was:', appName);
  
  var config = karate.read('classpath:config/AppConfig.json');  
  config.myEndPoints = karate.read('classpath:config/EndPoints.json');
  
   if (envName == 'PT140') {
       
		config.ENDPOINT_ACTIVATION= config.myEndPoints.PT140.ENDPOINT_ACTIVATION
		config.ENDPOINT_EARLY_RENEWAL_PENALTY= config.myEndPoints.PT140.ENDPOINT_EARLY_RENEWAL_PENALTY 
		config.ENDPOINT_MIGRATION_PENALTY= config.myEndPoints.PT140.ENDPOINT_MIGRATION_PENALTY 
		config.ENDPOINT_TERMINATION_PENALTY= config.myEndPoints.PT140.ENDPOINT_TERMINATION_PENALTY 
		config.ENDPOINT_REWARD_COMMITMENT= config.myEndPoints.PT140.ENDPOINT_REWARD_COMMITMENT 
		config.ENDPOINT_UPDATE_DEVICE_SERIAL_NO= config.myEndPoints.PT140.ENDPOINT_UPDATE_DEVICE_SERIAL_NO 
		config.ENDPOINT_RENEWAL= config.myEndPoints.PT140.ENDPOINT_RENEWAL 
		config.ENDPOINT_LIST_EARNED_TRANSACTIONS= config.myEndPoints.PT140.ENDPOINT_LIST_EARNED_TRANSACTIONS 
		config.ENDPOINT_GET_LOYALTY_ACCOUNT= config.myEndPoints.PT140.ENDPOINT_GET_LOYALTY_ACCOUNT 
		config.ENDPOINT_GET_EARLY_RENEWAL_PENALTY= config.myEndPoints.PT140.ENDPOINT_GET_EARLY_RENEWAL_PENALTY 
		config.ENDPOINT_GET_TERMINATION_PENALTY= config.myEndPoints.PT140.ENDPOINT_GET_TERMINATION_PENALTY 
		config.ENDPOINT_GET_BILLING_ACCOUNT_TERMINATION_PENALTY= config.myEndPoints.PT140.ENDPOINT_GET_BILLING_ACCOUNT_TERMINATION_PENALTY 
		config.ENDPOINT_GET_CHANGE_SERVICE_COMMITMENT_PENALTY= config.myEndPoints.PT140.ENDPOINT_GET_CHANGE_SERVICE_COMMITMENT_PENALTY 
		config.ENDPOINT_GET_MIGRATION_PENALTY= config.myEndPoints.PT140.ENDPOINT_GET_MIGRATION_PENALTY 
		config.ENDPOINT_GET_RESUME_PENALTY_ADJUSTMENTLIST= config.myEndPoints.PT140.ENDPOINT_GET_RESUME_PENALTY_ADJUSTMENTLIST 
		config.ENDPOINT_GET_RETURN_PENALTY_ADJUSTMENTLIST= config.myEndPoints.PT140.ENDPOINT_GET_RETURN_PENALTY_ADJUSTMENTLIST 
		config.ENDPOINT_FUTURE_ACTIVATION= config.myEndPoints.PT140.ENDPOINT_FUTURE_ACTIVATION 
		config.ENDPOINT_MIGRATION= config.myEndPoints.PT140.ENDPOINT_MIGRATION 
		config.ENDPOINT_SERVICE_CHANGE= config.myEndPoints.PT140.ENDPOINT_SERVICE_CHANGE 
		config.ENDPOINT_STATUS_CHANGE= config.myEndPoints.PT140.ENDPOINT_STATUS_CHANGE 
		config.ENDPOINT_OFFER_EXCHANGE= config.myEndPoints.PT140.ENDPOINT_OFFER_EXCHANGE 
		config.ENDPOINT_RETURN= config.myEndPoints.PT140.ENDPOINT_RETURN 
		config.ENDPOINT_CANCELLATION= config.myEndPoints.PT140.ENDPOINT_CANCELLATION 
		config.ENDPOINT_ADD_AGREEMENT_ITEM= config.myEndPoints.PT140.ENDPOINT_ADD_AGREEMENT_ITEM 
		config.ENDPOINT_RETURN_AGREEMENT_ITEM= config.myEndPoints.PT140.ENDPOINT_RETURN_AGREEMENT_ITEM 
		config.ENDPOINT_EXCHANGE_AGREEMENT_ITEM= config.myEndPoints.PT140.ENDPOINT_EXCHANGE_AGREEMENT_ITEM 
		config.ENDPOINT_VALIDATION_SUBSCRIPTION_MSC_LIST= config.myEndPoints.PT140.ENDPOINT_VALIDATION_SUBSCRIPTION_MSC_LIST 
		config.ENDPOINT_ADJUST_BALANCE= config.myEndPoints.PT140.ENDPOINT_ADJUST_BALANCE 
		config.ENDPOINT_UPDATE_DEVICE_SERIAL_NO= config.myEndPoints.PT140.ENDPOINT_UPDATE_DEVICE_SERIAL_NO 
		config.ENDPOINT_LOG_EVENT= config.myEndPoints.PT140.ENDPOINT_LOG_EVENT 
		config.ENDPOINT_UPDATE_COMMITMENT_ITEM= config.myEndPoints.PT140.ENDPOINT_UPDATE_COMMITMENT_ITEM
		config.ENDPOINT_ADJUST_REWARD_BALANCE= config.myEndPoints.PT140.ENDPOINT_ADJUST_REWARD_BALANCE
  	    config.ENDPOINT_LOG_EVENT= config.myEndPoints.PT140.ENDPOINT_LOG_EVENT
  	    config.ENDPOINT_EXCHANGE_AGREEMENT_ITEM=config.myEndPoints.PT140.ENDPOINT_EXCHANGE_AGREEMENT_ITEM
  	    config.ENDPOINT_NEW_ADJUST_BALANCE=config.myEndPoints.PT140.ENDPOINT_NEW_ADJUST_BALANCE
  	    
		
  	} else if (envName == 'PT148') {
  		
		config.ENDPOINT_ACTIVATION= config.myEndPoints.PT148.ENDPOINT_ACTIVATION
		config.ENDPOINT_EARLY_RENEWAL_PENALTY= config.myEndPoints.PT148.ENDPOINT_EARLY_RENEWAL_PENALTY 
		config.ENDPOINT_MIGRATION_PENALTY= config.myEndPoints.PT148.ENDPOINT_MIGRATION_PENALTY 
		config.ENDPOINT_TERMINATION_PENALTY= config.myEndPoints.PT148.ENDPOINT_TERMINATION_PENALTY 
		config.ENDPOINT_REWARD_COMMITMENT= config.myEndPoints.PT148.ENDPOINT_REWARD_COMMITMENT 
		config.ENDPOINT_UPDATE_DEVICE_SERIAL_NO= config.myEndPoints.PT148.ENDPOINT_UPDATE_DEVICE_SERIAL_NO 
		config.ENDPOINT_RENEWAL= config.myEndPoints.PT148.ENDPOINT_RENEWAL 
		config.ENDPOINT_LIST_EARNED_TRANSACTIONS= config.myEndPoints.PT148.ENDPOINT_LIST_EARNED_TRANSACTIONS 
		config.ENDPOINT_GET_LOYALTY_ACCOUNT= config.myEndPoints.PT148.ENDPOINT_GET_LOYALTY_ACCOUNT 
		config.ENDPOINT_GET_EARLY_RENEWAL_PENALTY= config.myEndPoints.PT148.ENDPOINT_GET_EARLY_RENEWAL_PENALTY 
		config.ENDPOINT_GET_TERMINATION_PENALTY= config.myEndPoints.PT148.ENDPOINT_GET_TERMINATION_PENALTY 
		config.ENDPOINT_GET_BILLING_ACCOUNT_TERMINATION_PENALTY= config.myEndPoints.PT148.ENDPOINT_GET_BILLING_ACCOUNT_TERMINATION_PENALTY 
		config.ENDPOINT_GET_CHANGE_SERVICE_COMMITMENT_PENALTY= config.myEndPoints.PT148.ENDPOINT_GET_CHANGE_SERVICE_COMMITMENT_PENALTY 
		config.ENDPOINT_GET_MIGRATION_PENALTY= config.myEndPoints.PT148.ENDPOINT_GET_MIGRATION_PENALTY 
		config.ENDPOINT_GET_RESUME_PENALTY_ADJUSTMENTLIST= config.myEndPoints.PT148.ENDPOINT_GET_RESUME_PENALTY_ADJUSTMENTLIST 
		config.ENDPOINT_GET_RETURN_PENALTY_ADJUSTMENTLIST= config.myEndPoints.PT148.ENDPOINT_GET_RETURN_PENALTY_ADJUSTMENTLIST 
		config.ENDPOINT_FUTURE_ACTIVATION= config.myEndPoints.PT148.ENDPOINT_FUTURE_ACTIVATION 
		config.ENDPOINT_MIGRATION= config.myEndPoints.PT148.ENDPOINT_MIGRATION 
		config.ENDPOINT_SERVICE_CHANGE= config.myEndPoints.PT148.ENDPOINT_SERVICE_CHANGE 
		config.ENDPOINT_STATUS_CHANGE= config.myEndPoints.PT148.ENDPOINT_STATUS_CHANGE 
		config.ENDPOINT_OFFER_EXCHANGE= config.myEndPoints.PT148.ENDPOINT_OFFER_EXCHANGE 
		config.ENDPOINT_RETURN= config.myEndPoints.PT148.ENDPOINT_RETURN 
		config.ENDPOINT_CANCELLATION= config.myEndPoints.PT148.ENDPOINT_CANCELLATION 
		config.ENDPOINT_ADD_AGREEMENT_ITEM= config.myEndPoints.PT148.ENDPOINT_ADD_AGREEMENT_ITEM 
		config.ENDPOINT_RETURN_AGREEMENT_ITEM= config.myEndPoints.PT148.ENDPOINT_RETURN_AGREEMENT_ITEM 
		config.ENDPOINT_EXCHANGE_AGREEMENT_ITEM= config.myEndPoints.PT148.ENDPOINT_EXCHANGE_AGREEMENT_ITEM 
		config.ENDPOINT_VALIDATION_SUBSCRIPTION_MSC_LIST= config.myEndPoints.PT148.ENDPOINT_VALIDATION_SUBSCRIPTION_MSC_LIST 
		config.ENDPOINT_ADJUST_BALANCE= config.myEndPoints.PT148.ENDPOINT_ADJUST_BALANCE 
		config.ENDPOINT_UPDATE_DEVICE_SERIAL_NO= config.myEndPoints.PT148.ENDPOINT_UPDATE_DEVICE_SERIAL_NO 
		config.ENDPOINT_LOG_EVENT= config.myEndPoints.PT148.ENDPOINT_LOG_EVENT 
		config.ENDPOINT_UPDATE_COMMITMENT_ITEM= config.myEndPoints.PT148.ENDPOINT_UPDATE_COMMITMENT_ITEM
		config.ENDPOINT_ADJUST_REWARD_BALANCE= config.myEndPoints.PT148.ENDPOINT_ADJUST_REWARD_BALANCE
  	    config.ENDPOINT_LOG_EVENT= config.myEndPoints.PT148.ENDPOINT_LOG_EVENT
  	    config.ENDPOINT_EXCHANGE_AGREEMENT_ITEM=config.myEndPoints.PT148.ENDPOINT_EXCHANGE_AGREEMENT_ITEM
  	    config.ENDPOINT_NEW_ADJUST_BALANCE=config.myEndPoints.PT148.ENDPOINT_NEW_ADJUST_BALANCE
   
    } else if (envName == 'PT168') {
    	
		config.ENDPOINT_ACTIVATION= config.myEndPoints.PT168.ENDPOINT_ACTIVATION
		config.ENDPOINT_EARLY_RENEWAL_PENALTY= config.myEndPoints.PT168.ENDPOINT_EARLY_RENEWAL_PENALTY 
		config.ENDPOINT_MIGRATION_PENALTY= config.myEndPoints.PT168.ENDPOINT_MIGRATION_PENALTY 
		config.ENDPOINT_TERMINATION_PENALTY= config.myEndPoints.PT168.ENDPOINT_TERMINATION_PENALTY 
		config.ENDPOINT_REWARD_COMMITMENT= config.myEndPoints.PT168.ENDPOINT_REWARD_COMMITMENT 
		config.ENDPOINT_UPDATE_DEVICE_SERIAL_NO= config.myEndPoints.PT168.ENDPOINT_UPDATE_DEVICE_SERIAL_NO 
		config.ENDPOINT_RENEWAL= config.myEndPoints.PT168.ENDPOINT_RENEWAL 
		config.ENDPOINT_LIST_EARNED_TRANSACTIONS= config.myEndPoints.PT168.ENDPOINT_LIST_EARNED_TRANSACTIONS 
		config.ENDPOINT_GET_LOYALTY_ACCOUNT= config.myEndPoints.PT168.ENDPOINT_GET_LOYALTY_ACCOUNT 
		config.ENDPOINT_GET_EARLY_RENEWAL_PENALTY= config.myEndPoints.PT168.ENDPOINT_GET_EARLY_RENEWAL_PENALTY 
		config.ENDPOINT_GET_TERMINATION_PENALTY= config.myEndPoints.PT168.ENDPOINT_GET_TERMINATION_PENALTY 
		config.ENDPOINT_GET_BILLING_ACCOUNT_TERMINATION_PENALTY= config.myEndPoints.PT168.ENDPOINT_GET_BILLING_ACCOUNT_TERMINATION_PENALTY 
		config.ENDPOINT_GET_CHANGE_SERVICE_COMMITMENT_PENALTY= config.myEndPoints.PT168.ENDPOINT_GET_CHANGE_SERVICE_COMMITMENT_PENALTY 
		config.ENDPOINT_GET_MIGRATION_PENALTY= config.myEndPoints.PT168.ENDPOINT_GET_MIGRATION_PENALTY 
		config.ENDPOINT_GET_RESUME_PENALTY_ADJUSTMENTLIST= config.myEndPoints.PT168.ENDPOINT_GET_RESUME_PENALTY_ADJUSTMENTLIST 
		config.ENDPOINT_GET_RETURN_PENALTY_ADJUSTMENTLIST= config.myEndPoints.PT168.ENDPOINT_GET_RETURN_PENALTY_ADJUSTMENTLIST 
		config.ENDPOINT_FUTURE_ACTIVATION= config.myEndPoints.PT168.ENDPOINT_FUTURE_ACTIVATION 
		config.ENDPOINT_MIGRATION= config.myEndPoints.PT168.ENDPOINT_MIGRATION 
		config.ENDPOINT_SERVICE_CHANGE= config.myEndPoints.PT168.ENDPOINT_SERVICE_CHANGE 
		config.ENDPOINT_STATUS_CHANGE= config.myEndPoints.PT168.ENDPOINT_STATUS_CHANGE 
		config.ENDPOINT_OFFER_EXCHANGE= config.myEndPoints.PT168.ENDPOINT_OFFER_EXCHANGE 
		config.ENDPOINT_RETURN= config.myEndPoints.PT168.ENDPOINT_RETURN 
		config.ENDPOINT_CANCELLATION= config.myEndPoints.PT168.ENDPOINT_CANCELLATION 
		config.ENDPOINT_ADD_AGREEMENT_ITEM= config.myEndPoints.PT168.ENDPOINT_ADD_AGREEMENT_ITEM 
		config.ENDPOINT_RETURN_AGREEMENT_ITEM= config.myEndPoints.PT168.ENDPOINT_RETURN_AGREEMENT_ITEM 
		config.ENDPOINT_EXCHANGE_AGREEMENT_ITEM= config.myEndPoints.PT168.ENDPOINT_EXCHANGE_AGREEMENT_ITEM 
		config.ENDPOINT_VALIDATION_SUBSCRIPTION_MSC_LIST= config.myEndPoints.PT168.ENDPOINT_VALIDATION_SUBSCRIPTION_MSC_LIST 
		config.ENDPOINT_ADJUST_BALANCE= config.myEndPoints.PT168.ENDPOINT_ADJUST_BALANCE 
		config.ENDPOINT_UPDATE_DEVICE_SERIAL_NO= config.myEndPoints.PT168.ENDPOINT_UPDATE_DEVICE_SERIAL_NO 
		config.ENDPOINT_LOG_EVENT= config.myEndPoints.PT168.ENDPOINT_LOG_EVENT 
		config.ENDPOINT_UPDATE_COMMITMENT_ITEM= config.myEndPoints.PT168.ENDPOINT_UPDATE_COMMITMENT_ITEM
		config.ENDPOINT_ADJUST_REWARD_BALANCE= config.myEndPoints.PT168.ENDPOINT_ADJUST_REWARD_BALANCE
  	    config.ENDPOINT_LOG_EVENT= config.myEndPoints.PT168.ENDPOINT_LOG_EVENT
  	    config.ENDPOINT_EXCHANGE_AGREEMENT_ITEM=config.myEndPoints.PT168.ENDPOINT_EXCHANGE_AGREEMENT_ITEM
  	    config.ENDPOINT_NEW_ADJUST_BALANCE=config.myEndPoints.PT168.ENDPOINT_NEW_ADJUST_BALANCE
    } 
   

  karate.configure('connectTimeout', 116000);
  karate.configure('readTimeout', 116000);
  return config;
}
